### ISSUE TITLE
Difference acknowledgment frame in GSDK3.2.1 and GSDK4.0.2

### ISSUE THREAD

**Issue by lancersky** [openthread/ot-efr32#333] opened 2022-06-19 03:15 UTC
Hi Experts,
I found that the ACK of GSDK3.2.1 and GSDK4.0.2 are different. I'm not sure which is correct.
Maybe this is the reason why commissioning failed with ST end device. #331 

<img width="1920" alt="无标题" src="https://user-images.githubusercontent.com/11283852/174464023-5b469686-00a0-4bd4-9780-84f06ceb2c46.png">

[sniffer.zip](https://github.com/openthread/ot-efr32/files/8934665/sniffer.zip)

**Comment by lancersky2017** [comment] 2022-06-21 03:58
Summary test result,
GSDK3.2.1,EFR32MG21F1024 as Commissioner,ST Sensor Joining OK
GSDK3.2.1,EFR32MG21F768 as Commissioner,nRF52840 Joining OK
GSDK3.2.1,EFR32MG21F768 as Commissioner,ST Sensor joining OK
GSDK4.0.2,EFR32MG21F768 as Commissioner,nRF52840 Joining OK
GSDK4.0.2,EFR32MG21F768 as Commissioner,ST Sensor Joining Failed
nRF52840 as Commissioner,ST Sensor Joining OK
[sniffer.zip](https://github.com/openthread/ot-efr32/files/8945638/sniffer.zip)

**Comment by suveshpratapa** [comment] 2022-06-23 02:37
@lancersky We have a set of incoming changes soon to address all the timing values in our platform layer corresponding to our latest GSDK release.  I will let you know when that is merged.

You said you notice success when you change `timings.rxToTx value to 192`.  What was the value there before you changed it?

**Comment by suveshpratapa** [comment] 2022-06-23 02:41
@lancersky We just recently merged a set of changes to bring support to our GSDK 4.1 release, along with adjustments to timings for CSL and improved ACK reaction times etc. Please try with the latest `ot-efr32` code and GSDK 4.1 if possible.  Please let me know if you can't move to the latest GSDK for any reason.  I would highly advise using the latest code.

**Comment by lancersky2017** [comment] 2022-06-23 02:45
Hi @suveshpratapa 
We also tried GSDK4.1.0, and the RCP firmware built from Simplicity Studio IDE. But the same fails.
This `timings.rxToTx` value is 256 in GSDK4.1.0 and the same with GSDK4.0.2.

**Comment by lancersky2017** [comment] 2022-06-23 02:58
Yeah,
We tried different platform solutions and lots of tests.
RCP firmware base on GSDK4.0.2 as Commissioner, the nrf52840 joining success, but the STM32WB not.
When I change and only change `timings.rxToTx` to 192, it solve the problem.
Is the cause of the problem as described in #334?

**Comment by suveshpratapa** [comment] 2022-06-23 02:59
@lancersky Let me get back to you in a day after discussing this further.  Thank you for the info in https://github.com/openthread/ot-efr32/issues/334

**Comment by suveshpratapa** [comment] 2022-09-26 17:12
@lancersky2017 I'm not sure if you've had any issues with this since we last talked?  Are you still waiting for any type of resolution?

PS. We advise you move to the latest SiLabs GSDK 4.1.1 to make use of further stability and performance fixes.

**Closed by suveshpratapa** 2022-09-26 17:12 UTC
