### ISSUE TITLE
Build failure saying no module named 'jinja2' on arch linux using pyenv

### ISSUE THREAD

**Issue by 0xlee** [openthread/ot-efr32#671] opened 2023-09-01 07:15 UTC
Hi,

I asked a question here: #665 

Here some information what error I get. I tried to install all dependencies manually, because I use arch linux. And I also used pyenv, because arch linux doesn't allow `pip install` on system installed python anymore.

So executing the build command, it says I don't have jinja2 module:

```
$ board="brd4166a"
$ ./script/build $board

<LINES OMITTED>

======================================================================
Generating 'openthread-efr32-soc' (yaml):
 - project file    : /home/dongha/projects/third/ot-efr32/src/platform_projects/openthread-efr32-soc.slcp
 - export_templates: /home/dongha/projects/third/ot-efr32/slc/exporter_templates/yaml
 - output dir      : /home/dongha/projects/third/ot-efr32/build/brd4166a/slc/soc
 - board           : brd4166a
======================================================================
+ run_slc -v 1 generate -data /home/dongha/projects/third/ot-efr32/build/brd4166a/slc/openthread_slc.data --sdk=/home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk --clear-cache --project-file=/home/dongha/projects/third/ot-efr32/src/platform_projects/openthread-efr32-soc.slcp --project-name=openthread-efr32-soc --output-type=makefile --no-copy --export-templates=/home/dongha/projects/third/ot-efr32/slc/exporter_templates/yaml --export-destination=/home/dongha/projects/third/ot-efr32/build/brd4166a/slc/soc --with brd4166a
+ IFS=' '
+ read -r -a slc_args
+ eval /home/dongha/projects/third/ot-efr32/slc/slc_cli/bin/slc-cli/slc-cli '-v 1 generate -data /home/dongha/projects/third/ot-efr32/build/brd4166a/slc/openthread_slc.data --sdk=/home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk --clear-cache --project-file=/home/dongha/projects/third/ot-efr32/src/platform_projects/openthread-efr32-soc.slcp --project-name=openthread-efr32-soc --output-type=makefile --no-copy --export-templates=/home/dongha/projects/third/ot-efr32/slc/exporter_templates/yaml --export-destination=/home/dongha/projects/third/ot-efr32/build/brd4166a/slc/soc --with brd4166a'
++ /home/dongha/projects/third/ot-efr32/slc/slc_cli/bin/slc-cli/slc-cli -v 1 generate -data /home/dongha/projects/third/ot-efr32/build/brd4166a/slc/openthread_slc.data --sdk=/home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk --clear-cache --project-file=/home/dongha/projects/third/ot-efr32/src/platform_projects/openthread-efr32-soc.slcp --project-name=openthread-efr32-soc --output-type=makefile --no-copy --export-templates=/home/dongha/projects/third/ot-efr32/slc/exporter_templates/yaml --export-destination=/home/dongha/projects/third/ot-efr32/build/brd4166a/slc/soc --with brd4166a
Instructed to delete cache: /home/dongha/.uc/slcc_components.cache
Deleted
Found valid project type for makefile
Generation location: /home/dongha/projects/third/ot-efr32/build/brd4166a/slc/soc
Generation: Starting AC generation for ucProject in project openthread-efr32-soc: Fri Sep 01 08:39:43 CEST 2023
Problems generating template files from component: board_control - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/hardware/board/src/sl_board_default_init.c.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
Problems generating template files from component: cmsis_core - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/CMSIS/template/RTE_Components.h.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
Problems generating template files from component: component_catalog - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/common/component_catalog/sl_component_catalog.h.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
Problems generating template files from component: device_init_clocks - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/service/device_init/template/sl_device_init_clocks.c.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
Problems generating template files from component: event_handler - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/service/event/template/sl_event_handler.h.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
Problems generating template files from component: event_handler - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/service/event/template/sl_event_handler.c.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
Problems generating template files from component: mbedtls_config - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/security/sl_component/sl_mbedtls_support/config/template/sli_mbedtls_config_autogen.h.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
Problems generating template files from component: mbedtls_config - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/security/sl_component/sl_mbedtls_support/config/template/sli_mbedtls_config_transform_autogen.h.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
Problems generating template files from component: ot_platform_abstraction_core - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/protocol/openthread/src/template/sl_ot_init.c.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
Problems generating template files from component: ot_platform_abstraction_core - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/protocol/openthread/include/template/sl_ot_init.h.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
Problems generating template files from component: psa_crypto_config - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/security/sl_component/sl_mbedtls_support/config/template/sli_psa_config_autogen.h.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
Problems generating template files from component: psa_crypto_config - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/security/sl_component/sl_mbedtls_support/config/template/sli_psa_builtin_config_autogen.h.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
Problems generating template files from component: toolchain_gcc - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/common/toolchain/gcc/linkerfile.ld.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
Problems generating template files from component: uartdrv_core - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/emdrv/uartdrv/init/sl_uartdrv_init.c.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
Problems generating template files from component: uartdrv_core - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/emdrv/uartdrv/init/sl_uartdrv_instances.h.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
Generation issue: com.silabs.ss.framework.uc.core.api.exception.MultiException: Multi-Exceptions available:
  Multi-Exceptions available:
  Problems generating template files from component: board_control - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/hardware/board/src/sl_board_default_init.c.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
  Problems generating template files from component: cmsis_core - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/CMSIS/template/RTE_Components.h.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
  Problems generating template files from component: component_catalog - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/common/component_catalog/sl_component_catalog.h.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
  Problems generating template files from component: device_init_clocks - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/service/device_init/template/sl_device_init_clocks.c.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
  Problems generating template files from component: event_handler - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/service/event/template/sl_event_handler.h.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
  Problems generating template files from component: event_handler - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/service/event/template/sl_event_handler.c.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
  Problems generating template files from component: mbedtls_config - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/security/sl_component/sl_mbedtls_support/config/template/sli_mbedtls_config_autogen.h.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
  Problems generating template files from component: mbedtls_config - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/security/sl_component/sl_mbedtls_support/config/template/sli_mbedtls_config_transform_autogen.h.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
  Problems generating template files from component: ot_platform_abstraction_core - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/protocol/openthread/src/template/sl_ot_init.c.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
  Problems generating template files from component: ot_platform_abstraction_core - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/protocol/openthread/include/template/sl_ot_init.h.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
  Problems generating template files from component: psa_crypto_config - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/security/sl_component/sl_mbedtls_support/config/template/sli_psa_config_autogen.h.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
  Problems generating template files from component: psa_crypto_config - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/security/sl_component/sl_mbedtls_support/config/template/sli_psa_builtin_config_autogen.h.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
  Problems generating template files from component: toolchain_gcc - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/common/toolchain/gcc/linkerfile.ld.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
  Problems generating template files from component: uartdrv_core - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/emdrv/uartdrv/init/sl_uartdrv_init.c.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
  Problems generating template files from component: uartdrv_core - Failed to generate template for /home/dongha/projects/third/ot-efr32/third_party/silabs/gecko_sdk/platform/emdrv/uartdrv/init/sl_uartdrv_instances.h.jinja... <class 'ModuleNotFoundError'>: No module named 'jinja2'
Generation to /home/dongha/projects/third/ot-efr32/build/brd4166a/slc/soc for openthread-efr32-soc did not succeed.
Project is already viable -- no choices need be made.
Command execution time (minus startup) : 6364 milliseconds
+ cleanup
+ :
+ cleanup
+ :
```

It seems to be a python error for me. I use pyenv with direnv, and it looks good to me

```
$ python
Python 3.11.4 (main, Aug 25 2023, 12:24:08) [GCC 13.2.1 20230801] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jinja2
>>>
$
$ which python
/home/dongha/projects/third/ot-efr32/.direnv/python-3.11/bin/python
```

And with system installed python looks also good:

```
$ python
Python 3.11.5 (main, Aug 28 2023, 20:02:58) [GCC 13.2.1 20230801] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jinja2
>>>
$
$ which python
/usr/bin/python
```

because I already installed [python-jinja](https://archlinux.org/packages/extra/any/python-jinja/) on arch linux.

I don't know which python installation it uses. But searching for slc-cli, I found this [documentation](https://www.silabs.com/documents/public/user-guides/ug520-software-project-generation-configuration-with-slc-cli.pdf). It says, I can use a different python by using `your\python\path slc`, but the slc-cli is a executable and the only slc I found is a bash file, which calls executes slc.jar with java. I am not a python developer, doesn't `your\python\path slc` work if slc is a python file?

What am I missing here?

I could use docker image as I already mentioned in #665. 

(Sorry, I am not a embedded developer nor a python developer. I am doing IoT just for my hobby.)

Thanks for your help 😊

**Comment by lmnotran** [comment] 2023-09-13 21:14
Hi @0xlee ,

That's a strange error, indeed. I was unable to reproduce your error in an `archlinux` docker container. Could you provide steps to reproduce the error?

For my testing, I created an `archlinux` container
```shell
docker pull archlinux
docker run --it archlinux bash
```

Then inside the container, I ran the following
```shell
# Install dependencies
pacman -Sy
pacman -S --no-confirm git git-lfs wget jre17-openjdk-headless unzip python3 python-jinja python-gitpython python-pyyaml cmake ninja

# Initialize git lfs hooks
git lfs install

# Download gcc-arm-none-eabi-10.3
cd /opt \
 && wget https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 \
 && tar xvf gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2

# Symlink gcc executables
ln -s /opt/gcc-arm-none-eabi-10.3-2021.10/bin/arm-none-eabi-* /usr/bin/

# Clone repo
git clone https://github.com/openthread/ot-efr32
cd ot-efr32/
git submodule update --init --recursive

# Build
cd /ot-efr32/
rm -rf build && ./script/build brd4161a
```

I was able to build successfully
```shell
[root@7ea196e9a007 ot-efr32]# rm -rf build && ./script/build brd4161a

<LINES OMITTED>

======================================================================
Generating 'openthread-efr32-soc' (yaml):
 - project file    : /ot-efr32/src/platform_projects/openthread-efr32-soc.slcp
 - export_templates: /ot-efr32/slc/exporter_templates/yaml
 - output dir      : /ot-efr32/build/brd4161a/slc/soc
 - board           : brd4161a
======================================================================
+ run_slc -v 1 generate -data /ot-efr32/build/brd4161a/slc/openthread_slc.data --sdk=/ot-efr32/third_party/silabs/gecko_sdk --clear-cache --project-file=/ot-efr32/src/platform_projects/openthread-efr32-soc.slcp --project-name=openthread-efr32-soc --output-type=makefile --no-copy --export-templates=/ot-efr32/slc/exporter_templates/yaml --export-destination=/ot-efr32/build/brd4161a/slc/soc --with brd4161a
+ IFS=' '
+ read -r -a slc_args
+ eval /ot-efr32/slc/slc_cli/bin/slc-cli/slc-cli '-v 1 generate -data /ot-efr32/build/brd4161a/slc/openthread_slc.data --sdk=/ot-efr32/third_party/silabs/gecko_sdk --clear-cache --project-file=/ot-efr32/src/platform_projects/openthread-efr32-soc.slcp --project-name=openthread-efr32-soc --output-type=makefile --no-copy --export-templates=/ot-efr32/slc/exporter_templates/yaml --export-destination=/ot-efr32/build/brd4161a/slc/soc --with brd4161a'
++ /ot-efr32/slc/slc_cli/bin/slc-cli/slc-cli -v 1 generate -data /ot-efr32/build/brd4161a/slc/openthread_slc.data --sdk=/ot-efr32/third_party/silabs/gecko_sdk --clear-cache --project-file=/ot-efr32/src/platform_projects/openthread-efr32-soc.slcp --project-name=openthread-efr32-soc --output-type=makefile --no-copy --export-templates=/ot-efr32/slc/exporter_templates/yaml --export-destination=/ot-efr32/build/brd4161a/slc/soc --with brd4161a
Instructed to delete cache: /root/.uc/slcc_components.cache
Deleted
Found valid project type for makefile
Generation location: /ot-efr32/build/brd4161a/slc/soc
Generation: Starting AC generation for ucProject in project openthread-efr32-soc: Wed Sep 13 21:05:16 GMT 2023
Generation: Starting AC generation for ProjectPostBuild in project openthread-efr32-soc: Wed Sep 13 21:05:17 GMT 2023
Generation: AC content generated for ucProject. Elapsed time: 793ms
Generation: AC content generated for ProjectPostBuild. Elapsed time: 21ms
Generation: Starting project generation for openthread-efr32-soc: Wed Sep 13 21:05:17 GMT 2023
Generation: Projects generated openthread-efr32-soc.Makefile
Elapsed time: 666ms
Total generation time: 1477 ms

Generation for openthread-efr32-soc to /ot-efr32/build/brd4161a/slc/soc has completed.
Command execution time (minus startup) : 8560 milliseconds
+ local slc_vars_file=/ot-efr32/build/brd4161a/slc/soc/slc_vars.yaml
+ mv /ot-efr32/build/brd4161a/slc/soc/openthread-efr32-soc.Makefile /ot-efr32/build/brd4161a/slc/soc/slc_vars.yaml
+ rm -f /ot-efr32/build/brd4161a/slc/soc/openthread-efr32-soc.project.mak
+ set +x


======================================================================
Generating 'openthread-efr32-soc' (CMake):
 - slc_vars_yaml file : /ot-efr32/build/brd4161a/slc/soc/slc_vars.yaml
 - export_templates   : /ot-efr32/slc/exporter_templates/platform_library
 - output dir         : /ot-efr32/build/brd4161a/slc/soc
 - board              : brd4161a
======================================================================
+ /ot-efr32/script/generate_cmake.py /ot-efr32/build/brd4161a/slc/soc/slc_vars.yaml /ot-efr32/build/brd4161a/slc/soc
... wrote /ot-efr32/build/brd4161a/slc/soc/CMakeLists.txt
... wrote /ot-efr32/build/brd4161a/slc/soc/mbedtls.cmake

<LINES OMITTED>

+ cleanup
+ '[' 0 -eq 14 ']'
+ ls -alh /ot-efr32/build/brd4161a/openthread/rcp_spi/bin/ot-rcp /ot-efr32/build/brd4161a/openthread/rcp_spi/bin/ot-rcp.s37 /ot-efr32/build/brd4161a/openthread/rcp_uart/bin/ot-rcp /ot-efr32/build/brd4161a/openthread/rcp_uart/bin/ot-rcp.s37 /ot-efr32/build/brd4161a/openthread/soc/bin/ot-cli-ftd /ot-efr32/build/brd4161a/openthread/soc/bin/ot-cli-ftd.s37 /ot-efr32/build/brd4161a/openthread/soc/bin/ot-cli-mtd /ot-efr32/build/brd4161a/openthread/soc/bin/ot-cli-mtd.s37 /ot-efr32/build/brd4161a/openthread/soc/bin/ot-ncp-ftd /ot-efr32/build/brd4161a/openthread/soc/bin/ot-ncp-ftd.s37 /ot-efr32/build/brd4161a/openthread/soc/bin/ot-ncp-mtd /ot-efr32/build/brd4161a/openthread/soc/bin/ot-ncp-mtd.s37
-rwxr-xr-x 1 root root 922K Sep 13 21:05 /ot-efr32/build/brd4161a/openthread/rcp_spi/bin/ot-rcp
-rwxr-xr-x 1 root root 298K Sep 13 21:05 /ot-efr32/build/brd4161a/openthread/rcp_spi/bin/ot-rcp.s37
-rwxr-xr-x 1 root root 938K Sep 13 21:05 /ot-efr32/build/brd4161a/openthread/rcp_uart/bin/ot-rcp
-rwxr-xr-x 1 root root 304K Sep 13 21:05 /ot-efr32/build/brd4161a/openthread/rcp_uart/bin/ot-rcp.s37
-rwxr-xr-x 1 root root 1.5M Sep 13 21:06 /ot-efr32/build/brd4161a/openthread/soc/bin/ot-cli-ftd
-rwxr-xr-x 1 root root 797K Sep 13 21:06 /ot-efr32/build/brd4161a/openthread/soc/bin/ot-cli-ftd.s37
-rwxr-xr-x 1 root root 1.4M Sep 13 21:06 /ot-efr32/build/brd4161a/openthread/soc/bin/ot-cli-mtd
-rwxr-xr-x 1 root root 635K Sep 13 21:06 /ot-efr32/build/brd4161a/openthread/soc/bin/ot-cli-mtd.s37
-rwxr-xr-x 1 root root 1.5M Sep 13 21:06 /ot-efr32/build/brd4161a/openthread/soc/bin/ot-ncp-ftd
-rwxr-xr-x 1 root root 789K Sep 13 21:06 /ot-efr32/build/brd4161a/openthread/soc/bin/ot-ncp-ftd.s37
-rwxr-xr-x 1 root root 1.4M Sep 13 21:06 /ot-efr32/build/brd4161a/openthread/soc/bin/ot-ncp-mtd
-rwxr-xr-x 1 root root 641K Sep 13 21:06 /ot-efr32/build/brd4161a/openthread/soc/bin/ot-ncp-mtd.s37
+ cleanup
+ :
[root@7ea196e9a007 ot-efr32]#

```

**Comment by 0xlee** [comment] 2023-09-18 11:41
Thanks for investing your time.

I am using pyenv, which is under the subdirectory of ot-efr32 (in my case ot-efr32/.direnv/python-3.11/bin/python). It should use this python version and the library located there.

But the `slc-cli` magically runs some python executable, but I don't know which python it uses. Is there a way to see what python executable it is using? I tried to find out with strace, but without any success.

Thanks and Best Regards
Dongha

**Comment by lmnotran** [comment] 2023-09-18 13:34
@0xlee I'm not a part of the team that develops `slc-cli`, but my best guess is that `slc-cli` uses the `python` distribution that is shipped with the tool.

```shell
lmnotran@lmnotran-ubuntu in ~/repos/ot-efr32
$ find . -executable -name 'python*' -type f

<LINES OMITTED>

./slc/slc_cli/bin/slc-cli/developer/adapter_packs/python/bin/python3.6m
./slc/slc_cli/bin/slc-cli/developer/adapter_packs/python/bin/python3.6
./slc/slc_cli/bin/slc-cli/developer/adapter_packs/python/bin/python3.6m-config
./slc/slc_cli/bin/slc-cli/developer/adapter_packs/python/bin/python3.6-config
./slc/slc_cli/bin/slc-cli/developer/adapter_packs/python/bin/python3-config
./slc/slc_cli/bin/slc-cli/developer/adapter_packs/python/bin/python3

<LINES OMITTED>

$ ./slc/slc_cli/bin/slc-cli/developer/adapter_packs/python/bin/python3
Python 3.6.7 (default, Apr 11 2022, 14:06:09)
[GCC 4.8.5] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jinja2
>>>
```

**Comment by lmnotran** [comment] 2023-09-27 18:23
Hi @0xlee,

Just checking in, are you still having issues with using `slc-cli`? If not, can we close this issue?

**Comment by lmnotran** [comment] 2023-10-05 15:39
Closing due to inactivity

**Closed by lmnotran** 2023-10-05 15:39 UTC
